"""Fixed-address menu and choice table declarations.

The patching algorithms remain in :mod:`time_twist.ui`; this module holds
the reviewed per-bank data they consume.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Bank-specific fixed-address record tables
# ---------------------------------------------------------------------------

# These are the canonical full-word menu labels. The release builder jointly
# packs the 11 large menu tables with dialogue, regenerates page pointers, and
# preserves each overlay's fixed suffix. TT1A's direct-address records below
# retain their individual byte lengths.

# TT1A keeps the blood-type choices in a fixed-address record table before
# its normal scenario groups. NOV2 directly references the fourth record at
# $A465, so the fixed-address slots retain their original byte lengths. Keep
# the semantic labels unpadded: the native and entropy builders pad the slot
# bytes separately. Semantic trailing spaces are visible to NOV2's dynamic
# selection-width capture and incorrectly push the right arrow outward.
TT1A_BLOOD_TYPE_PATCHES = (
    (0x025B, bytes.fromhex("0F 71 F4"), "A"),
    (0x025E, bytes.fromhex("CD 6E 3E 80"), "B"),
    (0x0262, bytes.fromhex("13 71 F4"), "O"),
    (0x0265, bytes.fromhex("0F 71 9A DC 7D"), "AB"),
)

# The month selector immediately follows the blood-type table.  It first
# offers January-June plus a July-December branch, then a second set for
# July-December.  Each label is chosen to fill exactly its original record.
TT1A_MONTH_PATCHES = (
    (0x026A, bytes.fromhex("D7 61 51 FA"), "Jan"),
    (0x026E, bytes.fromhex("D7 E1 51 FA"), "Feb"),
    (0x0272, bytes.fromhex("D8 61 51 FA"), "Mar"),
    (0x0276, bytes.fromhex("D8 E1 51 FA"), "Apr"),
    (0x027A, bytes.fromhex("D9 61 51 FA"), "May"),
    (0x027E, bytes.fromhex("D9 E1 51 FA"), "Jun"),
    (0x0282, bytes.fromhex("DA 61 51 04 90 BE 80"), "Jul-Dec"),
    (0x0289, bytes.fromhex("DA 61 51 FA"), "Jul"),
    (0x028D, bytes.fromhex("DA E1 51 FA"), "Aug"),
    (0x0291, bytes.fromhex("DB 61 51 FA"), "Sep"),
    (0x0295, bytes.fromhex("D7 6D F0 A8 FD"), "Oct"),
    (0x029A, bytes.fromhex("D7 6B B0 A8 FD"), "Nov"),
    (0x029F, bytes.fromhex("D7 6B F0 A8 FD"), "Dec"),
)

# The final fixed records before TT1A's first scenario group are its
# confirmation choices.  The English strings exactly retain their original
# packed lengths, so the scenario table that begins at $A4C2 does not move.
TT1A_CONFIRMATION_PATCHES = (
    (0x02A4, bytes.fromhex("04 33 3E 80"), "Yes"),
    (0x02A8, bytes.fromhex("63 71 F4"), "No"),
)

# TT1B's 53 museum command, object, and interaction labels precede the
# scenario groups. These source offsets/hash guard the original table; the
# English release repacks its records and updates the recovered page pointers.
TT1B_FIXED_TEXT_START_OFFSET = 0x09F7
TT1B_FIXED_TEXT_END_OFFSET = 0x0AC5
TT1B_FIXED_TEXT_SOURCE_SHA256 = (
    "AF6969B469081B6992DF4893FCE6308ABB51896B5D2DAAD49AF0B23500E5FD4F"
)
TT1B_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Move",
    "Sky",
    "Area",
    "Museum",
    "Sign",
    "Body",
    "East",
    "West",
    "Use",
    "Attack",
    "Poke",
    "Walk",
    "Jar",
    "Exhibit",
    "Room",
    "Girl",
    "Monster",
    "Charm",
    "Hold hands",
    "Hug",
    "Smile at",
    "Compliment",
    "Shout",
    "Eyes",
    "Nose",
    "Ears",
    "Chest",
    "Man",
    "Map",
    "North",
    "House",
    "Nameplate",
    "Intercom",
    "Newspaper",
    "Magnifying glass",
    "Picture",
    "Old man",
    "Outside",
    "Ground",
    "Forward",
    "Back",
    "Simon",
    "Deeper",
    "Listen",
    "Church",
    "Priest",
    "Congregant",
    "Sermon",
    "Devil",
    "Time Belt",
    "Run away",
)

# TT2's menu table contains commands, inventory/object labels, choice verbs,
# and twenty history-quiz answers. Records are selected by page plus index;
# English records may change length when the page pointers are regenerated.
TT2_FIXED_TEXT_START_OFFSET = 0x0BB6
TT2_FIXED_TEXT_END_OFFSET = 0x0CD8
TT2_FIXED_TEXT_SOURCE_SHA256 = (
    "FD956CF1D33EDA350549FC3079729458A1B8D20EFAF2D6883361E5FD8C3F0B9E"
)
TT2_DICTIONARY_POINTER_OFFSET = 0x0016
TT2_LOAD_ADDRESS = 0xA200
FIXED_UI_DICTIONARY_ENTRY_COUNT = 31
TT2_DICTIONARY_ENTRIES = FIXED_UI_DICTIONARY_ENTRY_COUNT
TT2_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Take",
    "Use",
    "Listen",
    "Smell",
    "Move",
    "Room",
    "Pierre",
    "Body",
    "Glass",
    "Wine",
    "Empty bottle",
    "Drink",
    "Robe",
    "Key",
    "Outside",
    "Info",
    "Walk",
    "Area",
    "Signboard",
    "Posted sign",
    "Bottles",
    "Wear",
    "Take off",
    "Old Man",
    "Damascus",
    "Jerusalem",
    "Crimea",
    "Hundred Years",
    "Pacific Ocean",
    "Merchants",
    "Citizens",
    "Entertainers",
    "Criminals",
    "Guide",
    "Zoid",
    "Geld",
    "Guild",
    "Oido",
    "da Vinci",
    "Lacoste",
    "De Palma",
    "De Niro",
    "Danube",
    "U Thant",
    "Tools",
    "Offer",
    "Toolbox",
    "Chino",
    "Gordo",
    "Wait",
    "No",
    "Lugot",
    "Accept",
    "Refuse",
    "Wine",
    "Official",
    "Onlookers",
    "Building",
    "Jail",
    "Town",
    "Jailer",
    "Women",
    "Basement",
    "Bishop",
    "Jeanne",
    "Rope",
    "Candle",
    "Cell",
)

# T22's command and object-name table uses the same page-indexed relocation
# as TT2. Source offsets and the hash below guard the Japanese input table.
T22_FIXED_TEXT_START_OFFSET = 0x0729
T22_FIXED_TEXT_END_OFFSET = 0x07A6
T22_FIXED_TEXT_SOURCE_SHA256 = (
    "AF59D34E1084B43CC754BB24582D85FE7B085C0C478E65A2DD21F0ACA1D7D44F"
)
T22_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Use",
    "Listen",
    "Move",
    "Baron",
    "Jailer",
    "Women",
    "Robe",
    "Key",
    "Pact",
    "Take off",
    "Basement",
    "Outside",
    "Take",
    "Push",
    "Room",
    "Chino",
    "Wall",
    "Rope",
    "Hole",
    "Cell",
    "Open",
    "Box",
    "Scrap paper",
    "Back",
    "Scaffold",
    "Jeanne",
    "Bishop",
    "Lugot",
    "Onlookers",
    "Prison",
    "Walk",
)

# TT3A's menu table contains POW-camp, town, resistance, and quiz labels.
TT3A_FIXED_TEXT_START_OFFSET = 0x0A04
TT3A_FIXED_TEXT_END_OFFSET = 0x0BAC
TT3A_FIXED_TEXT_SOURCE_SHA256 = (
    "7CBFBAF8AEAE3831B8F9BB0E4A53BF746171BF554F8B7E6ADE7DBFE0AF47DCBA"
)
TT3A_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Take",
    "Use",
    "Move",
    "Area",
    "Body",
    "Pocket",
    "Pliers",
    "Outside fence",
    "Hit",
    "Info",
    "Room",
    "Wall",
    "Charm",
    "Outside",
    "Push",
    "Enter",
    "Walk",
    "Floor",
    "Nick",
    "Ralph",
    "Frankie",
    "Stove",
    "Bed",
    "Shower room",
    "Sheet",
    "Clothes",
    "Mattress",
    "Tile",
    "Pebble",
    "Shower",
    "Wear",
    "Tunnel",
    "Soil",
    "Front",
    "Back",
    "Soldier",
    "Yes",
    "No",
    "Gun",
    "Throw",
    "Wire fence",
    "Woods",
    "Bench",
    "Man",
    "Simon",
    "Red writing",
    "Blue writing",
    "Notes",
    "Password",
    "Greeting",
    "Crumple",
    "Burn",
    "Tear",
    "Combine",
    "North",
    "East",
    "West",
    "Watermill",
    "Fountain",
    "Bottle",
    "Saw it",
    "Didn't see",
    "South",
    "Take out",
    "Paper",
    "Back",
    "Trash can",
    "Old man",
    "Gestapo",
    "Ghetto",
    "Residence",
    "Résistance",
    "Register",
    "Gunboat",
    "Nazi boat",
    "U-boat",
    "Banana boat",
    "Gabin",
    "Delon",
    "Belmondo",
    "Philippe",
    "Truffaut",
    "Mont",
    "Patton",
    "Eisenhower",
    "Roosevelt",
    "Churchill",
    "MacA.",
    "Yes",
    "No",
    "Broom",
    "Streetlamp",
    "Woman",
)

# TT3B's menu table contains action, object, and battle labels.
TT3B_FIXED_TEXT_START_OFFSET = 0x0420
TT3B_FIXED_TEXT_END_OFFSET = 0x0477
TT3B_FIXED_TEXT_SOURCE_SHA256 = (
    "999B38FD507E1B5777D893C1009551E63FBD9153DCDB59A383BAC72313A9D8E4"
)
TT3B_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Take",
    "Use",
    "Move",
    "Area",
    "Watermill",
    "Simon",
    "Woman",
    "Gun",
    "Charm",
    "Schmidt",
    "Outside car",
    "Fight",
    "Defend",
    "Run away",
    "Listen",
    "Read",
    "Text",
    "Hitler",
    "Cougar",
)

# TT4's menu table contains commands, medical-treatment choices, characters,
# objects, the five-sages logic puzzle, and Greek history-quiz answers.
TT4_FIXED_TEXT_START_OFFSET = 0x0CD3
TT4_FIXED_TEXT_END_OFFSET = 0x0E8B
TT4_FIXED_TEXT_SOURCE_SHA256 = (
    "B28692367059E8AB5396FF23552FDD2E2279130845EA2964F05E1F7EA19D377C"
)
TT4_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Treat",
    "Use",
    "Silver coin",
    "Move",
    "Room",
    "Statue",
    "Priest",
    "Head",
    "Slap cheeks",
    "Press abdomen",
    "Lift chin",
    "Bend knees",
    "Cover ears",
    "Cover eyes",
    "Pinch nose",
    "With pauses",
    "Continuously",
    "Olive",
    "Oil",
    "Bell",
    "Give",
    "Eat",
    "Lick",
    "Outside",
    "Area",
    "Building",
    "Merchant",
    "Man",
    "Body",
    "Sell",
    "Buy",
    "Medicinal herb",
    "No",
    "Temple",
    "South",
    "Info",
    "Dario",
    "Youth",
    "Raise",
    "Lower",
    "Level",
    "Warm",
    "Cool",
    "Massage",
    "Squeeze",
    "Prick",
    "Leave it",
    "Apply oil",
    "Wrap with cloth",
    "North",
    "East",
    "West",
    "Girl",
    "Mother",
    "Plantain herb",
    "Fish mint",
    "Jiaogulan",
    "Grind",
    "Boil",
    "Road",
    "Take",
    "Soldier",
    "Spear",
    "Swing",
    "Back",
    "Walk",
    "Socrates",
    "Pythagoras",
    "Plato",
    "Herodotus",
    "Homer",
    "Sea",
    "Fisherman",
    "Child",
    "Nicras",
    "Polis",
    "Alice",
    "Imelda",
    "Jakarta",
    "Sparta",
    "Daedalus",
    "Heracles",
    "Napoleon",
    "Gorbachev",
    "Agamemnon",
    "Kannon",
    "Partisan",
    "Aisnon",
    "Parthenon",
    "Strawberry",
    "Melon",
    "Fig",
    "Brown rice",
    "Pearl",
    "Coffee",
)

# TT5's menu table contains actions, plantation tasks and quantities,
# American-history quiz answers, livestock puzzle digits, bottle controls,
# and late-chapter locations.
TT5_FIXED_TEXT_START_OFFSET = 0x0AA5
TT5_FIXED_TEXT_END_OFFSET = 0x0C92
TT5_FIXED_TEXT_SOURCE_SHA256 = (
    "443013AA1921DD6EDDC01E5C38E301624D27BFDCD8B4525DE237451751E44D54"
)
TT5_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Listen",
    "Move",
    "George",
    "Belle",
    "Men",
    "Area",
    "Ruins",
    "Hoofprints",
    "North",
    "East",
    "West",
    "Take",
    "Open",
    "Info",
    "Room",
    "Money",
    "Window",
    "Drawer",
    "Outside",
    "Use",
    "Cotton",
    "Yes",
    "No",
    "Okay",
    "Again",
    "Schedule",
    "Call Meyer",
    "Water",
    "Pick cotton",
    "Repair roof",
    "Split wood",
    "Pull weeds",
    "4 cups",
    "6 cups",
    "8 cups",
    "10 cups",
    "25 baskets",
    "26 baskets",
    "27 baskets",
    "28 baskets",
    "1 place",
    "2 places",
    "3 places",
    "4 places",
    "60 centimeters",
    "65 centimeters",
    "70 centimeters",
    "75 centimeters",
    "30 minutes",
    "60 minutes",
    "90 minutes",
    "120 minutes",
    "Tom",
    "Trader",
    "Marine Corps",
    "Cavalry",
    "Red ship",
    "White ship",
    "Black ship",
    "Madame Dewi",
    "Mrs. Stowe",
    "Mrs. Akino",
    "Mrs. Mary",
    "Whitney",
    "Kilauea",
    "Etna",
    "Rushmore",
    "Oiwake",
    "Projector",
    "Cotton gin",
    "Plow",
    "Camera",
    "Airplane",
    "VCR",
    "Back",
    "Answer",
    "Problem",
    "Cow",
    "Sheep",
    "Pig",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Tens digit",
    "Ones digit",
    "Zero",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six or more",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Pour in",
    "Finish",
    "Large bottle",
    "Medium bottle",
    "Small bottle",
    "Mansion",
    "Meyer",
    "Cave",
    "Statue",
    "Inside",
)

# T25's 42 menu records contain mansion and flooded-island actions/objects.
T25_FIXED_TEXT_START_OFFSET = 0x098A
T25_FIXED_TEXT_END_OFFSET = 0x0A43
T25_FIXED_TEXT_SOURCE_SHA256 = (
    "5B96A30331E8E68609B817B068A41F32ECDF3D8AB8A7C667D85CD3E612270DF6"
)
T25_FIXED_TEXT_RECORDS = (
    "Look",
    "Talk",
    "Use",
    "Move",
    "Sky",
    "Soldier",
    "Coffee",
    "Offer",
    "Mansion",
    "Room",
    "Wagon",
    "Meyer",
    "George",
    "Lincoln",
    "Pot",
    "Outside",
    "Outside window",
    "Hallway",
    "Area",
    "Guest room",
    "Study",
    "Stairs",
    "Take",
    "Open",
    "Desk",
    "Drawer",
    "First drawer",
    "Second drawer",
    "Third drawer",
    "Picture",
    "Listen",
    "Hide",
    "Get down",
    "Go up",
    "Get on",
    "Boat",
    "Coyote",
    "River",
    "Me",
    "Coyote 1",
    "Coyote 2",
    "Coyote 3",
)

# TT6A's fixed table contains the donkey-specific verbs and the Nazareth
# village, home, and workshop object labels.
TT6A_FIXED_TEXT_START_OFFSET = 0x0547
TT6A_FIXED_TEXT_END_OFFSET = 0x05EC
TT6A_FIXED_TEXT_SOURCE_SHA256 = (
    "BAB73CA358662FF6D05E52B84AF7327850B3D29DAD118E19EDB5F53C6A548270"
)
TT6A_FIXED_TEXT_RECORDS = (
    "Look",
    "Listen",
    "Smell",
    "Hold",
    "Move",
    "Area",
    "Sky",
    "Body",
    "Joseph",
    "Nod",
    "Turn aside",
    "Sleeve",
    "Village",
    "Drink",
    "Info",
    "Elder",
    "Child",
    "Well",
    "Trough",
    "Rope",
    "Hay",
    "Well water",
    "Hill",
    "Right house",
    "Left house",
    "River",
    "Room",
    "Mary",
    "Bowl",
    "Hand mill",
    "Bracelet",
    "Necklace",
    "Wheat",
    "Outside",
    "Get on",
    "Get down",
    "Tools",
    "Stand",
    "On stand",
    "Roof tile",
    "Children",
)

# TT6B's menu table contains travel, stable-animal, history-quiz, and animal
# interaction labels.
TT6B_FIXED_TEXT_START_OFFSET = 0x0580
TT6B_FIXED_TEXT_END_OFFSET = 0x0687
TT6B_FIXED_TEXT_SOURCE_SHA256 = (
    "DABABCA65A7EB469E1CD0EB41B2711D9B2721FFD3C011676442C28193EE50B6B"
)
TT6B_FIXED_TEXT_RECORDS = (
    "Look",
    "Listen",
    "Smell",
    "Hold",
    "Move",
    "Area",
    "Joseph",
    "Mary",
    "Body",
    "Sleeve",
    "Glare",
    "Shout",
    "Stick out tongue",
    "Wink",
    "Talk",
    "Eat",
    "Tent",
    "Camel",
    "Men",
    "North",
    "East",
    "West",
    "South",
    "Forward",
    "Back",
    "Attack",
    "Walk",
    "Room",
    "Trough",
    "Horse",
    "Sheep",
    "Cow",
    "Dung",
    "Fruit of wisdom",
    "Fruit of knowledge",
    "Isis",
    "Baal",
    "Jehovah",
    "Iraq",
    "Jordan",
    "Syria",
    "Egypt",
    "David",
    "Solomon",
    "Samson",
    "Jacob",
    "Isaac",
    "Saddam",
    "Abraham",
    "Satan",
    "Christ",
    "Zoroaster",
    "Oil",
    "Hay",
    "Wag tail",
    "Fleas",
    "Hug",
    "Smile at",
    "Compliment",
    "Hoof",
    "Tail",
    "Mane",
)

# TT6C's menu table contains finale actions and answer choices from earlier
# chapters. The release rebuilds its page pointers after joint compression.
TT6C_FIXED_TEXT_START_OFFSET = 0x08B8
TT6C_FIXED_TEXT_END_OFFSET = 0x0A4F
TT6C_FIXED_TEXT_SOURCE_SHA256 = (
    "580A8C45C48A3D468FA446DC6D4294A32D5CF78DFB76C630E63D8BB6282606BD"
)
TT6C_FIXED_TEXT_RECORDS = (
    "Look",
    "Devil",
    "Leap at",
    "Take",
    "Jar",
    "Talk",
    "Listen",
    "Eat",
    "Use",
    "Room",
    "Joseph",
    "Mary",
    "Baby",
    "Men",
    "My body",
    "Kashim",
    "Body",
    "Time Belt",
    "Move aside",
    "Open",
    "Move",
    "Area",
    "Ground",
    "Hole",
    "Panel",
    "Yes",
    "Lid",
    "North",
    "East",
    "West",
    "South",
    "Read",
    "Human bones",
    "Picture",
    "Text",
    "Outside",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Cougar",
    "Ruger",
    "Hauer",
    "Berger",
    "Glazier",
    "Blacksmith",
    "Tavern",
    "Tailor",
    "Catherine",
    "Mylene",
    "Laura",
    "Isabel",
    "Morocco",
    "Rebecca",
    "Bread",
    "Trad",
    "Austria",
    "France",
    "Switzerland",
    "Belgium",
    "Plantain herb",
    "Jiaogulan",
    "Fish mint",
    "Swertia",
    "Daedalus",
    "Centaur",
    "Atlas",
    "Cerberus",
    "Fred",
    "Bob",
    "Tom",
    "Jim",
    "Serow",
    "Coyote",
    "Reindeer",
    "Puma",
    "Gold bracelet",
    "Silver bracelet",
    "Copper bracelet",
    "Tin bracelet",
    "Magdala",
    "Nazareth",
    "Bethlehem",
    "Jerusalem",
    "Bishop",
    "Meyer",
    "Hitler",
    "Nicras",
    "Jeanne",
    "Alexander",
    "Lincoln",
    "Left",
    "Up",
    "Right",
)
