"""Rebuild the definitive native title authorities from the historical IPS.

The supplied ``TimeTwist-Zenpen-newlogo.ips`` is the visual authority for the
English TIME TWIST wordmark.  This tool applies that patch to the exact supported
Japanese Zenpen image, extracts the patched NOV4 final title at native NES
resolution, and derives the monochrome swipe from the same pixel silhouette.

The original game image and IPS are maintainer-supplied inputs and are never
redistributed by this repository.  Release builds consume only the checked-in
256x240 indexed PNG authorities generated by this tool.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from PIL import Image

from time_twist.fds import FdsImage
from time_twist.title import (
    FINAL_NAMETABLE_START,
    TITLE_CHR_OFFSET,
    TITLE_CHR_SIZE,
    TITLE_PALETTE,
    _render_indexed_nametable,
    decode_title_rle,
)

BASE_ZENPEN_SHA256 = (
    "B9424DD29EE195A9FA9AC4F844F058C380E30F7ACA741218789FA8611F741916"
)
DEFINITIVE_IPS_SHA256 = (
    "915C0ED3600F5E560F9F588DC2100FE59772B5F7570E4F183565FBA9C77C6BA2"
)
FINAL_FILE_SHA256 = (
    "220E1755BEBFCEFCA408D5E18A323FC6AE9EDEB03C3B01CA22B30163A2E0016F"
)
FINAL_PIXELS_SHA256 = (
    "EA50A1888635F7A8FE863C61EB6D728CE260D281FABF3259E2FED700BC75CBA8"
)
SLIDE_FILE_SHA256 = (
    "5218681DB3BC8F7631DC69BFB0B6A3C242B55B8018D3319CF9EC94C14DF10CA8"
)
SLIDE_PIXELS_SHA256 = (
    "7FA164F34514B568560F5FC4BE7186719A692EB1013E7B00A26DE9FAE61080AB"
)


def _sha256(data: bytes) -> str:
    """Return an uppercase SHA-256 digest."""
    return hashlib.sha256(data).hexdigest().upper()


def _apply_ips(source: bytes, patch: bytes) -> bytes:
    """Apply a standard IPS patch and return a new byte string."""
    if not patch.startswith(b"PATCH"):
        raise ValueError("definitive logo patch is not an IPS file")
    output = bytearray(source)
    offset = 5
    while True:
        if patch[offset : offset + 3] == b"EOF":
            offset += 3
            break
        if offset + 5 > len(patch):
            raise ValueError("truncated IPS record")
        target = int.from_bytes(patch[offset : offset + 3], "big")
        size = int.from_bytes(patch[offset + 3 : offset + 5], "big")
        offset += 5
        if size:
            end = offset + size
            if end > len(patch):
                raise ValueError("truncated IPS payload")
            payload = patch[offset:end]
            offset = end
        else:
            if offset + 3 > len(patch):
                raise ValueError("truncated IPS RLE record")
            run = int.from_bytes(patch[offset : offset + 2], "big")
            value = patch[offset + 2]
            offset += 3
            if run == 0:
                raise ValueError("zero-length IPS RLE record")
            payload = bytes((value,)) * run
        end = target + len(payload)
        if end > len(output):
            output.extend(b"\x00" * (end - len(output)))
        output[target:end] = payload
    if offset != len(patch):
        # A three-byte IPS truncate size is legal after EOF, but this authority
        # does not use it. Reject drift rather than silently changing the image.
        raise ValueError("unexpected data after IPS EOF marker")
    return bytes(output)


def _indexed_png(
    image: Image.Image, palette: tuple[tuple[int, int, int], ...]
) -> Image.Image:
    """Return an indexed copy with the explicit production display palette."""
    result = Image.new("P", image.size, 0)
    result.putdata(image.get_flattened_data())
    flat = [channel for color in palette for channel in color]
    result.putpalette(flat + [0] * (768 - len(flat)))
    return result


def build_native_titles(
    zenpen_path: Path,
    ips_path: Path,
) -> tuple[Image.Image, Image.Image]:
    """Extract the exact final logo and derive its exact monochrome swipe."""
    zenpen = zenpen_path.read_bytes()
    patch = ips_path.read_bytes()
    if _sha256(zenpen) != BASE_ZENPEN_SHA256:
        raise ValueError(
            "Zenpen image does not match the definitive logo source"
        )
    if _sha256(patch) != DEFINITIVE_IPS_SHA256:
        raise ValueError("IPS does not match the definitive logo patch")

    patched = FdsImage.from_bytes(_apply_ips(zenpen, patch))
    matches = [
        entry
        for side in patched.sides
        for entry in side.files
        if entry.name == "NOV4" and entry.load_address == 0xA200
    ]
    if len(matches) != 1:
        raise ValueError(
            f"expected one patched NOV4 file, found {len(matches)}"
        )
    nov4 = matches[0].data
    final_nametable, _ = decode_title_rle(nov4, FINAL_NAMETABLE_START)
    title_chr = nov4[TITLE_CHR_OFFSET : TITLE_CHR_OFFSET + TITLE_CHR_SIZE]
    if len(title_chr) != TITLE_CHR_SIZE:
        raise ValueError("patched NOV4 title CHR is truncated")

    rendered = _render_indexed_nametable(final_nametable, title_chr)
    final_l = Image.new("L", (256, 240), 0)
    final_l.paste(rendered.crop((0, 0, 256, 97)), (0, 0))
    final = _indexed_png(final_l, TITLE_PALETTE)

    # The swipe uses exactly the same logo geometry. NOV4's moving viewport is
    # 96 pixels high, so row 96 belongs only to the final colored state.
    slide_l = Image.new("L", (256, 240), 0)
    final_pixels = final_l.load()
    slide_pixels = slide_l.load()
    if final_pixels is None or slide_pixels is None:
        raise ValueError("Pillow did not expose title pixel access")
    for y in range(96):
        for x in range(256):
            slide_pixels[x, y] = 1 if final_pixels[x, y] else 0
    slide = _indexed_png(slide_l, (TITLE_PALETTE[0], TITLE_PALETTE[1]))
    return final, slide


def _verify_output(final: Image.Image, slide: Image.Image) -> None:
    """Fail closed if regenerated pixel authorities drift."""
    if _sha256(final.tobytes()) != FINAL_PIXELS_SHA256:
        raise ValueError("regenerated final title pixels drifted")
    if _sha256(slide.tobytes()) != SLIDE_PIXELS_SHA256:
        raise ValueError("regenerated slide pixels drifted")


def main() -> None:
    """Regenerate both checked-in title authorities from maintainer inputs."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "zenpen", type=Path, help="untouched Japanese Zenpen FDS"
    )
    parser.add_argument("ips", type=Path, help="definitive new-logo IPS")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("work/title_assets"),
    )
    args = parser.parse_args()
    final, slide = build_native_titles(args.zenpen, args.ips)
    _verify_output(final, slide)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    final_path = args.output_dir / "Time Twist approved native title.png"
    slide_path = args.output_dir / "Time Twist approved native slide.png"
    final.save(final_path, optimize=False)
    slide.save(slide_path, optimize=False)
    # Pixel identity is the contract. File hashes are also published for the
    # checked-in canonical encodings, but Pillow versions may encode PNG chunks
    # differently when maintainers deliberately regenerate them.
    print(f"final pixels: {_sha256(final.tobytes())}")
    print(f"slide pixels: {_sha256(slide.tobytes())}")
    print(final_path)
    print(slide_path)


if __name__ == "__main__":
    main()
